### ISSUE TITLE
External containers support via IServiceProviderFactory<TContainerBuilder>

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical.Windows#113]
- ~~Can Startup and Exit handlers be automatically handled?~~ No
- [x] Implementation #247 
- [x] documentation https://github.com/RadicalFx/documentation/pull/113
- [x] release (blocked by https://github.com/appveyor/ci/issues/3386)
- [x] Craft a sample https://github.com/RadicalFx/documentation/pull/119

**Comment by mauroservienti** [comment]
- https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacServiceProviderFactory.cs
- https://github.com/unitycontainer/microsoft-dependency-injection/blob/7c23b4724bb8d4f85d5f54adaa922415fab3b8da/src/Extensions/HostingExtension.cs

**Comment by mauroservienti** [comment]
This sounds truly interesting https://laurentkempe.com/2019/09/03/WPF-and-dotnet-Generic-Host-with-dotnet-Core-3-0/

**Comment by mauroservienti** [comment]
This is way more complex than expected due to the way external containers integrate with IServiceCollection (Autofac for good reasons does a completely different thing to what Unity does for example).

It seems that the simplest approach is to leverage the general host builder as demonstrated in this [blog post](https://laurentkempe.com/2019/09/03/WPF-and-dotnet-Generic-Host-with-dotnet-Core-3-0/). The problem is that, I have a spike that attempts to use it, the Radical ApplicationBootstrapper lifecycle is completely orthogonal to the HostBuilder one making the integration very hard. The only options seem to be:

- do not provide this in 2.0.0 or in 2.1.0 as it’ll be a huge breaking change and wait for 3.0.0 that we never even talked about
- delay 2.0.0 to get this in by revamping the ApplicationBootstrapper

@nazarenomanco @micdenny thoughts?

**Comment by mauroservienti** [comment]
With #210 it is possible to create a WPF application that uses the same approach as always but with a new simpler API:

```
public partial class App : Application
{
    public App()
    {
        this.AddRadicalApplication(configuration => 
        {
            configuration.UseAsShell<Presentation.MainView>();
        });
    }
}
``` 

Or one that uses the generic host:

```
public partial class App : Application
{
    public App()
    {
        var host = new HostBuilder()
            .AddRadicalApplication(configuration =>
            {
                configuration.UseAsShell<Presentation.MainView>();
            })
            .Build();

        Startup += async (s, e) => 
        {
            await host.StartAsync();
        };

        Exit += async (s, e) =>
        {
            using (host)
            {
                await host?.StopAsync();
            }
        };
    }
}
```

The generic host one is more verbose, however, it allows using all the host feature among which containers pluggability:

```
var host = new HostBuilder()
    .UseServiceProviderFactory(new AutofacServiceProviderFactory())
    .AddRadicalApplication(configuration => 
    {
        //...
    })
    .Build();
```

Which makes plugging in all containers supporting `Microsoft.Extensions.DependencyInjection` trivially easy.

#210 still needs a lot of testing before being able to be merged.

**Comment by micdenny** [comment]
I like the generic host way

**Comment by mauroservienti** [comment]
Raised #214 and #213 to bring the new RadicalApplication model to life. Once that's in we can implement this in a new minor and in a separate package, e.g. `Radical.Windows.Hosting`, as I don't think it makes sense to add to `Radical.Windows` a dependency on the new Generic Hosting model.

**Comment by mauroservienti** [comment]
2.0.0-RC.3 with generic host support is out of the door 🎉
