### ISSUE TITLE
Partial convention should be Partials (plural)

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical.Windows#206]
We should move the lookup logic for partials to use `Partials` as namespace segment instead of `Partial`. And for backward compatibility go on also searching in `Partial`.

- [x] Code: https://github.com/RadicalFx/Radical.Windows/pull/296
- [x] Doc: https://github.com/RadicalFx/documentation/pull/146

**Comment by nazarenomanco** [comment]
@mauroservienti done
