### ISSUE TITLE
AutoCommandBindings does not correctly bind if the VM method ends with "Command"

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical.Windows#3]
_From @mauroservienti on March 26, 2014 10:19_

_Copied from original issue: RadicalFx/Radical#48_

**Comment by mauroservienti** [comment]
https://github.com/melkio should already have a fix for this.

**Comment by mauroservienti** [comment]
A proposed fix could be:
* stop removing the Command suffix;
* given an AutoCommandBinding to "Foo"
* look for both Foo and FooCommand and take the first if both are found (same for the "fact" name);

If the the binding is already set to FooCommand we end up looking for FooCommand and FooCommandCommand but given that we take the first it not an issue.

**Comment by mauroservienti** [comment]
failing tests added.

**Comment by micdenny** [comment]
> failing tests added.

the build on appveyor is failing because of this, should we [Ignore] the test in the meanwhile?

**Comment by micdenny** [comment]
sorry, I did it :smile: can't wait to see if the build works fine ;)

**Comment by mauroservienti** [comment]
My fault I should have created them on a branch. Ignore them


Sent by Outlook for Android





On Sun, Aug 23, 2015 at 4:01 AM -0700, "Michael Denny" <notifications@github.com> wrote:












sorry, I did it  can't wait to see if the build works fine ;)
