### ISSUE TITLE
Add WindowsManager Behavior

### ISSUE THREAD

**Issue by nazarenomanco** [RadicalFx/Radical.Windows#34]

**Comment by nazarenomanco** [comment]
@mauroservienti  please check

**Comment by nazarenomanco** [comment]
Ops... probably I forgot to create a branch... If it is a problem I can delete everything and create a correct PR. Sorry.

**Comment by mauroservienti** [comment]
yes, please. Use a dedicated branch.

**Comment by nazarenomanco** [comment]
This is already in Radical.Widows... probably I was out of sync.
@mauroservienti  may we close this issue?

**Comment by mauroservienti** [comment]
non c' `e nulla nella [PR](https://github.com/RadicalFx/Radical.Windows/issues/35) non ci sono modifiche

**Comment by nazarenomanco** [comment]
Nel senso che cancellata e ripresa la fork WindowsManager c'è già.  
Mi sa che mi ero "incasinato" con branch e modifiche

**Comment by mauroservienti** [comment]
OK, allora chiudo

**Comment by nazarenomanco** [comment]
https://github.com/RadicalFx/Radical.Windows/commit/25cd166413e3ba8aa1db48638bb05a0400124586
