### ISSUE TITLE
Add DataGridBehavior

### ISSUE THREAD

**Issue by nazarenomanco** [RadicalFx/Radical.Windows#36]
* [x] [code](https://github.com/RadicalFx/Radical.Windows/issues/37)
* [x] [doco](https://github.com/RadicalFx/Radical/wiki/DataGrid-Behavior)

**Comment by mauroservienti** [comment]
Can you please add documentation as well: https://github.com/RadicalFx/Radical/wiki/DataGrid-Behavior

**Comment by nazarenomanco** [comment]
Is it possible to change the structure of the Wiki in:
DataGird
   . LastColumnFill

Thank you

**Comment by mauroservienti** [comment]
Just dump some info in that document, docs will be soon migrated https://github.com/RadicalFx/documentation/issues/2

**Comment by nazarenomanco** [comment]
@mauroservienti please check the documetation :thought_balloon:

**Comment by mauroservienti** [comment]
I like it.

**Comment by mauroservienti** [comment]
@nazarenomanco is this done?

**Comment by nazarenomanco** [comment]
Yes

**Comment by mauroservienti** [comment]
Fixed by #42
