### ISSUE TITLE
Extend the WindowControlBoxBehavior to incorporate the WindowManager to better align components

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical.Windows#38]
We now have a [WindowManager](https://github.com/RadicalFx/Radical.Windows/commit/25cd166413e3ba8aa1db48638bb05a0400124586) that works with attached properties, would be interesting to share the same behavior with the [WindowControlBoxBehavior](https://github.com/RadicalFx/Radical.Windows/blob/develop/src/net35/Radical.Windows/Presentation/Behaviors/WindowControlBoxBehavior.cs)

**Comment by nazarenomanco** [comment]
You mean move the attached properties in the WindowControlBoxBehavior?

**Comment by mauroservienti** [comment]
No, the idea is to have both or better the idea is: if the thing has more than one attached property then use a behavior that is statefull and much easier to write. Can be done later, not urgent.

**Comment by nazarenomanco** [comment]
:+1: 
I'll forgot it :smile:

**Comment by nazarenomanco** [comment]
@mauroservienti we have to create a new behavior (WindowBehavior) that has all these features?

**Comment by mauroservienti** [comment]
removed from 1.6.0 milestone to speed up things.

**Comment by nazarenomanco** [comment]
@mauroservienti please check extend_windowcontrolboxbehavior before I create a PR. 

Some doubt:

1. We have removed WindowMoanager. May this be considered a breaking change?
2. Do we have to move "SetWindowPos" to NativeMethods?
3. Where I can put/find a WPF test project to test the correct implementation?

Thanks

**Comment by mauroservienti** [comment]
@nazarenomanco create a PR, it's much easier to discuss changes using the PR diff.

**Comment by mauroservienti** [comment]
Fixed by https://github.com/RadicalFx/Radical.Windows/commit/41e6876b2bef19f4ef4757a077a5f77aec02fbf0
