### ISSUE TITLE
Correct implementation of EnumBooleanConverter

### ISSUE THREAD

**Issue by nazarenomanco** [RadicalFx/Radical.Windows#40]
It does not work correctly in some cases changing the property in the ViewModel

**Comment by mauroservienti** [comment]
Can you list the scenario in which it fails?

**Comment by nazarenomanco** [comment]
In some cases changing the value of the property on the ViewModel do not update the view. 
The new implementation allows to check better values of the enum on the View with this syntax:

ConverterParameter={x:Static local:myEnum.FristEnum}}
